### ISSUE TITLE
[v0.12.0] I'm missing the table module

### ISSUE THREAD

**Issue by pkel** [janestreet/incr_dom_widgets#2]
I observe that you dropped the `Table` module from v0.12.0. Is this permanent? I've made `Table` work with https://github.com/ocaml/opam-repository/pull/13452 after https://github.com/janestreet/base/issues/67 was fixed and am ready to share if appreciated.

**Comment by xclerc** [comment]
There has been a bit of reorganization; the `Table` module
now lives in the `incr_dom_partial_render` library:
  https://github.com/janestreet/incr_dom_partial_render/blob/master/src/table.mli

**Comment by pkel** [comment]
Thanks! I missed that.
